ivan-dev to master
GnomeTV/mail_swift_course pull request #10
Opened 2020-10-27 13:31 UTC by GnomeTV

2020-10-27 13:34 UTC, kovalchuk0803 requested changes

2020-10-27 13:34 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/LoginViewController.swift
> +            emailTextField.heightAnchor.constraint(equalToConstant: 24.0).isActive = true
а че константами leftInset и rightInset не пользуемся?
ну собсна это бы везде поправить

2020-10-27 13:50 UTC, GnomeTV commented on CAFS/CAFS/PresentationLayer/LoginViewController.swift
> +            emailTextField.heightAnchor.constraint(equalToConstant: 24.0).isActive = true
поправлю

2020-10-27 14:14 UTC, kovalchuk0803 requested changes
вынеси в константы все, повторяющиеся штуки
типа высоты текст филда высоты индикатора, около каждой цифры чтоль писать

2020-10-28 08:40 UTC, kovalchuk0803 requested changes

2020-10-28 08:40 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/LoginViewController.swift
> +    private let topInsertIndicator: CGFloat = 3.0
Insert? Inset наверно ?) ну и непонятно че за растрояние
Назови его чтоль insetToTextField

2020-10-29 20:59 UTC, closed without merging