Add class FirestoreManager
GnomeTV/mail_swift_course pull request #13
Opened 2020-10-29 21:32 UTC by Determinant179

2020-10-30 08:17 UTC, kovalchuk0803 requested changes

2020-10-30 08:17 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +
нужен интерфейс
protocol IFirestoreManager {
   func addDocument(бла бла бла)
}

2020-10-30 08:17 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +    let db : Firestore
зачем она наружу торчит?
ей наверно private нужен

2020-10-30 08:17 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +        self.db = db
а зачем инит, let db = Firestore.firestore()
Зачем вне этого класса вообще кому-то знать про FireStore
FireStore - это всего лишь способ реализации бд

2020-10-30 08:17 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +                     lastname : String,
Какой-то очень конкретный метод, его лучше вынести обертку для FirestoreManager, а в этом классе сделать все более общим

2020-10-30 08:17 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +
ну вот смотри
все что нужно этому методу это название коллекции "users" и какой-то словарь с параметрами
сделай метод insertData(toCollection collection: String, params: [String: String], _ onErrorReceived: @escaping (error: Error) -> ())

2020-10-30 08:17 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +        db.collection("users").document(id).delete() { err in
опять зачем-то завязываешься на "users", передавай как параметр, а такой метод для обертки этого класса оставь

2020-10-30 08:17 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +            } else {
ошибку надо возвращать, а то ее не обработать никак

2020-10-30 08:17 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +                      lastname : String = "",
такая же проблема как и предыдущих методах

2020-10-30 08:17 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +        if (firstname != "") {
есть же firstName.isEmpty

2020-10-30 08:17 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +                      firstname : String = "",
Так много параметров что выглядит ужасно, не лучше ли структуру передавать?
С ними как будто и работать удобней

2020-10-30 08:17 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +            } else {
Ошибку не возвращаешь

2020-10-30 08:17 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/CoreAssembly.swift
> +
В CoreLayer не добавил

2020-11-01 11:48 UTC, GnomeTV approved these changes

2020-11-02 10:49 UTC, Arhangel69 approved these changes

2020-11-02 10:50 UTC, merged

2020-11-02 12:10 UTC, Determinant179 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +                     lastname : String,
Понимаю, но не знаю как

2020-11-02 12:11 UTC, Determinant179 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +
toCollection collection: String, params[] - это структура?

2020-11-02 12:12 UTC, Determinant179 commented on CAFS/CAFS/CoreLayer/CoreAssembly.swift
> +
Дописать в протоколы ICoreAssembly?