Fix bags
GnomeTV/mail_swift_course pull request #15
Opened 2020-11-04 14:08 UTC by Determinant179

2020-11-04 14:50 UTC, kovalchuk0803 requested changes

2020-11-04 14:50 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/CoreAssembly.swift
> +    var firestoreManager : FirestoreManager { get }
IFireStore

2020-11-04 14:50 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/CoreAssembly.swift
> +    var firestoreManager : FirestoreManager { get }
через протокол, писал же уже

2020-11-04 14:50 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +    func addDocument(collection : String, params : [String : Any], _ onErrorReceived: @escaping (_ error: Error) -> ())
еще я подумал, и наверно это неправильно немного называется, лучше назвать onErrorReceived как completion и вызывать его в любом случае в независимости от ошибки
_ completion: @escaping (_ error: Error?) -> () вот так
А то получается что невозможно узнать когда метод выполнится

2020-11-04 14:50 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +            in
а здесь просто вызывать вот так newDocument.setData(params, completion)

2020-11-04 14:50 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +            in
ну и для всех методов это сделать

2020-11-04 14:50 UTC, kovalchuk0803 commented on CAFS/Podfile
> +  pod 'FirebaseFirestoreSwift'
зачем???
он же выше и так написан

2020-11-04 17:39 UTC, Determinant179 commented on CAFS/CAFS/CoreLayer/CoreAssembly.swift
> +    var firestoreManager : FirestoreManager { get }
> через протокол, писал же уже

Не понял
Этот протокол же в другом файле, где класс описывается

2020-11-04 18:21 UTC, Alyo135 requested changes

2020-11-04 18:21 UTC, Alyo135 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +    func editDocument(collection : String, id : String, params : [String : Any], _ completion: @escaping (_ error: Error?
чет я не втыкаю схему с id и param?
сразу нормальный словарь почему нельзя передать?

2020-11-05 12:08 UTC, Arhangel69 approved these changes

2020-11-05 12:09 UTC, Arhangel69 submitted a review, later dismissed

2020-11-06 16:54 UTC, Alyo135 requested changes

2020-11-06 16:54 UTC, Alyo135 commented on CAFS/CAFS/CoreLayer/CoreAssembly.swift
> +    var firestoreManager : FirestoreManager { get }
так и не поменял

2020-11-06 16:54 UTC, Alyo135 commented on CAFS/Podfile
> +  pod 'FirebaseFirestoreSwift'
это не убрал

2020-11-07 18:16 UTC, GnomeTV submitted a review, later dismissed

2020-11-08 11:32 UTC, GnomeTV approved these changes

2020-11-09 12:41 UTC, GnomeTV approved these changes

2020-11-09 12:42 UTC, Arhangel69 approved these changes

2020-11-09 18:00 UTC, merged