Dev registration view controller
GnomeTV/mail_swift_course pull request #20
Opened 2020-11-10 17:55 UTC by Arhangel69

2020-11-10 18:47 UTC, Alyo135 requested changes

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/AppResources/AppDelegate.swift
> +        let window = UIWindow()
а это зачем?
просто window = UIWindow(frame: UIScreen.main.bounds)
все норм же было

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +    private func addNewUserDocument(collection: String, id: String, data : PersonalDataDoc, _ completion: @escaping (_ error: Error?) -> Void) {
какое-то кривое название PersonalDataDoc

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +            try db.collection(collection).document(id).setData(from: data)
лучше использовать методы, которые я написал, Codable по сути означает, что объект можно превратить в Data, не нужно лишних кастов писать, там внутри огоньбазы все само вызовется

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +    func addNewUser(personalData : PersonalData) {
FireStoreManager не должен ничего про юзеров каких-то знать, это слой выше

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +                print("Error adding document: \(err)")
ошибку надо в комплшне возвращать

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/CoreLayer/Hasher.swift
> +func genHash(string : String) -> String
это лучше вынести в extension к String

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/PresentationLayer/LoginScreen/LoginViewController.swift
> +        /*if false {
не оставляйте такого

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/PresentationLayer/LoginScreen/LoginViewController.swift
>          print("Register")
принт наверно уже убрать можно?

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/PresentationLayer/PersonalData.swift
> +        self.firstname = firstname
а зачем так-то?

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/PresentationLayer/PersonalData.swift
> +    private var firstname = ""
сделайте публичными и уберите эти методы, они никакой задачи не решают

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/PresentationLayer/PersonalData.swift
> +    let firstname : String
а почему нельзя пользоваться PersonalData?

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
>          print("Register")
принт убрать?

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +            let firestoreManager = FirestoreManager()
здесь не должно быть файрстора, есть ViewModel глянь в примере

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +        if firstNameTextField.text == "" {
а если nil?)))

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +            personalData.setFirstname(firstname: firstNameTextField.text ?? "default")
какой еще default
все сломается же, в базу default запишется

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +        if firstNameTextField.text == "" {
надо обработку в отдельный метод вынести

2020-11-10 18:47 UTC, Alyo135 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +            universityiTextField.attributedPlaceholder = NSAttributedString(string: "Введите ваш университет", attributes: [NSAttributedString.Key.foregroundColor: UIColor.systemRed])
NSAttributedString(string: "Введите ваш университет", attributes: [NSAttributedString.Key.foregroundColor: UIColor.systemRed])
это бы тоже в extension вынести

2020-11-25 09:11 UTC, Arhangel69 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +    private func addNewUserDocument(collection: String, id: String, data : PersonalDataDoc, _ completion: @escaping (_ error: Error?) -> Void) {
Ветка development
Данный класс удален в связи с его ненадобностью.

2020-11-25 09:12 UTC, Arhangel69 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +    private func addNewUserDocument(collection: String, id: String, data : PersonalDataDoc, _ completion: @escaping (_ error: Error?) -> Void) {
@Alyo135 
Ветка development.
Удалено с связи с перестройкой другого кода.

2020-11-25 09:13 UTC, Arhangel69 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +            try db.collection(collection).document(id).setData(from: data)
@Alyo135 
Ветка development.
Переделано.

2020-11-25 09:14 UTC, Arhangel69 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +    func addNewUser(personalData : PersonalData) {
@Alyo135 
Ветка development.
Функционал по добавлению пользователей перенесен в класс UserManager.

2020-11-25 09:19 UTC, Arhangel69 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +                print("Error adding document: \(err)")
@Alyo135 
Ветка development.
Изменено в связи с перестройкой кода.

2020-11-25 09:19 UTC, Arhangel69 commented on CAFS/CAFS/CoreLayer/Hasher.swift
> +func genHash(string : String) -> String
@Alyo135 
Ветка development.
Сделано.

2020-11-25 09:34 UTC, Arhangel69 commented on CAFS/CAFS/PresentationLayer/PersonalData.swift
> +        self.firstname = firstname
@Alyo135 
Ветка development.
Класс обновлен.

2020-11-25 09:35 UTC, Arhangel69 commented on CAFS/CAFS/PresentationLayer/LoginScreen/LoginViewController.swift
>          print("Register")
@Alyo135 
Пока что нужен для отладки. Нужен способ, чтобы в релизной сборке эти принты игнорировались,

2020-11-25 09:35 UTC, Arhangel69 commented on CAFS/CAFS/PresentationLayer/PersonalData.swift
> +    private var firstname = ""
@Alyo135 
Ветка development.
Класс обновлен.

2020-11-25 09:36 UTC, Arhangel69 commented on CAFS/CAFS/PresentationLayer/PersonalData.swift
> +    let firstname : String
@Alyo135 
Ветка development.
Класс обновлен.
Был введен из-за того, что при передаче в FirestoreManager в базу закладывались также служебные поля.

2020-11-25 09:38 UTC, Arhangel69 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
>          print("Register")
@Alyo135
Пока что нужен для отладки. Нужен способ, чтобы в релизной сборке эти принты игнорировались.

2020-11-25 09:40 UTC, Arhangel69 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +            let firestoreManager = FirestoreManager()
@Alyo135
Ветка development.
Код перестроен.

2020-11-25 09:49 UTC, Arhangel69 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +        if firstNameTextField.text == "" {
@Alyo135
Да вроде не должен...

2020-11-25 09:51 UTC, Arhangel69 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +            personalData.setFirstname(firstname: firstNameTextField.text ?? "default")
@Alyo135
Ветка development.
Переписан частично класс.

2020-11-25 09:51 UTC, Arhangel69 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +        if firstNameTextField.text == "" {
@Alyo135
Ветка development.
Вынесено.

2020-11-25 17:22 UTC, closed without merging