Development
GnomeTV/mail_swift_course pull request #23
Opened 2020-11-18 17:55 UTC by Arhangel69

2020-11-18 17:59 UTC, GnomeTV approved these changes

2020-11-25 12:45 UTC, kovalchuk0803 requested changes

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +    internal let db: Firestore
если ничего не писать оно будет internal 
но я не понимаю зачем это наружу торчит причем только через класс, хотя оперировать надо протоколами

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +    func addNewDocument<T : Codable>(collection : String, id : String, data: inout T, _ completion: @escaping (_ error: Error?) -> Void) {
зачем Data inout?
T - назови как-то покрасивше

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/Hasher.swift
> +        //return String(format: "%02X", SHA512.hash(data: [UInt8](self.utf8)).hashValue)
коменты кода - зло

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/Hasher.swift
> +        return String(format: "%02X", self.hash)
return необязательно писать кстати)

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/UserManager.swift
> +class UserManager : FirestoreManager {
не надо наследования
лучше все протоколами

заводишь переменную private let fireStoreManager: IFireStoreManager и уже с ней работаешь

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/UserManager.swift
> +        super.addNewDocument(collection: collection, id: id, data: &pData) { err in
как будто completion просто параметром передать можно, он же такой же как и в firestore manager

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/CoreLayer/UserManager.swift
> +    func isUserExist(id : String, _ completion: @escaping (_ result: Bool?) -> Void) {
есть enum Result который больше подходит для этого

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/LoginScreen/LoginViewController.swift
> +        if emailTextField.text == "" {
заведи переменную let email = emailTextField.text
она еще может быть nil
== ""  то же самое что isEmpty

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/MainTabBarController.swift
> +        UITabBar.appearance().backgroundImage = UIImage()
это вот что-то нехорошее
почему внутри класса мы к какому-то синглтону обращаемся когда сто проц у нас и так есть эти параметры
еще я сомневаюсь в работоспособности этого кода при нескольких таббарах

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/PersonalData.swift
> +    /*init(from decoder: Decoder) throws {
коменты кода - зло

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/PersonalData.swift
> +        return email.genHash()
ваще хэш же совпасть может
в свифте есть штука такая UUID().string что-то такое, я думаю найдете
но это так, здесь можно так оставить ибо тестовый проект

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/PersonalData.swift
> +    func getEmail() -> String {
ну это хрень какая-то
не надо делать методы для set-a и get-a переменных в свифте есть модификаторы доступа
можно сделать private, private(set) - это как ридонли и только внутри класса можно поменять
можно вообще ридонли везде сделать, так что этот класс ваще полностью надо переделать

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/ProfileViewController.swift
> +    lazy var screenWidth = screenRect.size.width
lazy вычисляются при вызове один раз
если у тебя поменяется ориентация или у тебя просто айпад - то такое не сработает

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +extension Optional where Wrapped == String {
воу воу, а чем String не угодил?

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +extension Optional where Wrapped == String {
это как-то ваще тупо что-то проверять если там nil

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +    lazy private var userManager = UserManager()
это надо из ServiceAssembly или PresentationAssembly брать при текущей архитектуре, или выпилите тогда ненужное

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +        if firstNameTextField.text == "" {
let name = firstNameTextField.text

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +                        self.isEmailExists = true
а ты уверен что здесь главная очередь?
я вот очень сомневаюсь, а если главная, то значит надо в менеджере очередь асинхронную сделать

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +        do {
а do тут к чему?

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/PresentationLayer/RegistrationViewController.swift
> +            isPersonalDataValid() { [self] isValid in
weak self?
self и так в capture list попадает
правда в свифте 5.3 на этот счет были какие-то изменения, так что проверь

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/ServiceLayer/AlertService.swift
> +
ойвэй, здесь все плохо
сделай extension к UIAlertConrtroller

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/ServiceLayer/ServicesAssembly.swift
> +    let alertService: IAlertService = AlertService() as! IAlertService
зачем здесь as! IAlertService
AlertService не подписан на IAlertService - это краш

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/ServiceLayer/ServicesAssembly.swift
> +    let alertService: IAlertService = AlertService() as! IAlertService
ваще убери этот сервис, он не нужен

2020-11-25 12:45 UTC, kovalchuk0803 commented on CAFS/CAFS/ServiceLayer/ServicesAssembly.swift
> +    let alertService: IAlertService = AlertService() as! IAlertService
и кстати UserManager должен быть здесь
и все обращения к нему должны быть отсюда

2020-11-27 11:42 UTC, Arhangel69 commented on CAFS/CAFS/CoreLayer/FirestoreManager.swift
> +    func addNewDocument<T : Codable>(collection : String, id : String, data: inout T, _ completion: @escaping (_ error: Error?) -> Void) {
Решено.

2020-11-27 15:54 UTC, Arhangel69 commented on CAFS/CAFS/PresentationLayer/PersonalData.swift
> +        return email.genHash()
Надо тогда переделывать структуру данных в Firestore. UUID генерирует каждый раз новый уникальный UID, а здесь необходимо при одних и тех же исходных данных получать одно и то же значение.

2020-11-27 21:15 UTC, Arhangel69 commented on CAFS/CAFS/PresentationLayer/MainTabBarController.swift
> +        UITabBar.appearance().backgroundImage = UIImage()
Отдельно вроде как нет appearance(), так что пока других вариантов нет.

2020-11-28 12:19 UTC, Determinant179 approved these changes

2020-11-28 12:21 UTC, merged